version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db
    environment:
      DATABASE_HOST: 60.204.136.42
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: user

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
