//GET  http://localhost:3000/api/products/list


# GET  http://localhost:3000/api/products/getProductId?id=1


# POST  http://localhost:3000/api/products/addProduct
# Content-Type: application/json

# {
# 	"id":101,
# 	"name":"Product101",
# 	"type":"OKKKK"
# }

DELETE  http://localhost:3000/api/products/deleteProduct?id=101