

@type = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMDUsIm5hbWUiOiJ3YW5nd3UiLCJpYXQiOjE3Mzk0MzY3MzksImV4cCI6MTczOTQ0MDMzOSwiYXVkIjoiNjAuMjA0LjEzNi40MjozMDAwIiwiaXNzIjoiNjAuMjA0LjEzNi40MjozMDAwIn0.LMNUFs7OC7k0TVncMNmAI2-XZ-xz6G4-jLkpiMvr-qk
GET  http://localhost:3000/api/user/list?page=1&pageSize=10&name=wan&sex=F
Content-Type: {{type}}
Authorization: Bearer {{token}}



# GET  http://localhost:3000/api/products/getProductId?id=1


# POST  http://localhost:3000/api/products/addProduct
# Content-Type: application/json

# {
# 	"id":101,
# 	"name":"Product101",
# 	"type":"OKKKK"
# }

# DELETE  http://localhost:3000/api/products/deleteProduct?id=101


# POST  http://localhost:3000/api/auth/sign-in
# Content-Type: application/json

# {
# 	"name":"wangwu",
# 	"password":"123456"
# }

